### ISSUE TITLE
Error when loading commands.

### ISSUE THREAD

**Issue by cristiioan** [Advanced-Command-Handler/Advanced-Command-Handler#63]
[24 15:50:02.483][LOADING] Advanced Command Handler 2.2.2 by Ayfri.
[24 15:50:02.523][LOADING] Client initialized.
[24 15:50:02.526][LOADING] Loading commands.
[24 15:50:02.526][LOADING] Categories : (5)
[24 15:50:02.527][LOADING] Commands in the category 'economy' : (2)
[24 15:50:02.529][LOADING] TypeError: command.getInvalidPermissions is not a function
    at loadCommand (/home/cristiioan/Desktop/mcdiscord/node_modules/advanced-command-handler/dist/classes/CommandHandler.js:121:44)
    at async loadCommands (/home/cristiioan/Desktop/mcdiscord/node_modules/advanced-command-handler/dist/classes/CommandHandler.js:144:21)
    at async Object.launch (/home/cristiioan/Desktop/mcdiscord/node_modules/advanced-command-handler/dist/classes/CommandHandler.js:90:13)
[24 15:50:04.167][ERROR] An error occurred. 
TypeError: CommandHandler.prefixes.push is not a function
    at Object.launch (/home/cristiioan/Desktop/mcdiscord/node_modules/advanced-command-handler/dist/classes/CommandHandler.js:102:33)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by Ayfri** [comment]
Which version of Node.js to you use?
Do you use the default message event?

**Comment by cristiioan** [comment]
I use the one you put in examples and node 15

**Comment by Ayfri** [comment]
In my examples, the code isn't updated or isn't using the last version of my handler (I do not have time to update everything), so it might be normal, try using the default message event or copying it and modifying it.

**Comment by cristiioan** [comment]
When I use the default message event i still get this error.

**Comment by Ayfri** [comment]
Can you show me the code of the first command in the `economy` category? (Via a gist or a hastebin)

**Comment by cristiioan** [comment]
I can. But when i will be on my pc.

**Comment by Ayfri** [comment]
Can you provide this quick? The next update is ready!

**Comment by cristiioan** [comment]
https://pastebin.com/Q4ancULh

**Comment by Ayfri** [comment]
Mh that's weird... Firstly, the `ownerOnly` property doesn't exist in the latest versions of this project, secondly, I'm not sure if adding properties to the CommandHandler namespace don't break things.

**Comment by Ayfri** [comment]
Say if you find a fix, I'm publishing the new update.

**Comment by TakeFy** [comment]
Hey i'm getting this issue in local host is working but not on vps with same node v lmao 
![image](https://user-images.githubusercontent.com/62612084/106379411-0c7d6000-63ac-11eb-816b-625b5e318dd6.png)

**Comment by TakeFy** [comment]
> Mh that's weird... Firstly, the `ownerOnly` property doesn't exist in the latest versions of this project, secondly, I'm not sure if adding properties to the CommandHandler namespace don't break things.

and why owner only is not existing anymore it was so useful

**Comment by TakeFy** [comment]
and i really need to update my bot : (

**Comment by TakeFy** [comment]
I test to duplicate the folder of the bot that is working and it's giving error

**Comment by TakeFy** [comment]
https://sourceb.in/hMTlGQhXT6

**Comment by Ayfri** [comment]
So @TakeFy also got this error in #67, it occurs when you have a file in your commands that is not a command, please verify if you don't have something similar and if yes, you just have to move the file.

**Comment by Ayfri** [comment]
Reopen if you still have the issue.
